"""empty message

Revision ID: 9e3e39fd0bc0
Revises: 1fbb85ca6e18
Create Date: 2021-04-15 02:31:55.622503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3e39fd0bc0'
down_revision = '1fbb85ca6e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.String(length=120), nullable=False),
    sa.Column('father_id', sa.String(length=80), nullable=False),
    sa.Column('mother_id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship')
    # ### end Alembic commands ###
